/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuarterlyUpdate } from '../models/quarterly-update';
export interface QuartersResponse {
  cumulativeEstimatedTaxLiability?: number;
  quarters?: Array<QuarterlyUpdate> | null;
  totalNetProfitSubmitted?: number;
}
