/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuarterUpdateResponse {
  allowableExpenses?: number;
  businessId?: number;
  id?: string | null;
  message?: string | null;
  netProfit?: number;
  quarterName?: string | null;
  status?: string | null;
  taxYear?: string | null;
  taxableIncome?: number;
}
