/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuarterSubmissionResponse } from '../../models/quarter-submission-response';

export interface ApiQuarterIdSubmitPost$Params {
  id: string;
}

export function apiQuarterIdSubmitPost(http: HttpClient, rootUrl: string, params: ApiQuarterIdSubmitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<QuarterSubmissionResponse>> {
  const rb = new RequestBuilder(rootUrl, apiQuarterIdSubmitPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuarterSubmissionResponse>;
    })
  );
}

apiQuarterIdSubmitPost.PATH = '/api/quarter/{id}/submit';
