/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuartersResponse } from '../../models/quarters-response';

export interface ApiQuartersGet$Params {
}

export function apiQuartersGet(http: HttpClient, rootUrl: string, params?: ApiQuartersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<QuartersResponse>> {
  const rb = new RequestBuilder(rootUrl, apiQuartersGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuartersResponse>;
    })
  );
}

apiQuartersGet.PATH = '/api/quarters';
